# Gradle Properties
group = com.github.rootavd
version = 1.0.0

pluginName = RootAVD Manager
pluginId = com.github.rootavd.plugin
vendorName = RootAVD Team

# Target Android Studio version
platformVersion = 2023.2.1.1
platformType = AI
sinceBuild = 232

# Opt-out flag for bundling Kotlin standard library -> https://jb.gg/intellij-platform-kotlin-stdlib
kotlin.stdlib.default.dependency = false

org.gradle.configuration-cache = true
org.gradle.caching = true

pluginRepositoryUrl = https://github.com/